.TH mount_cd9660_image 1
.SH NAME
.PP
 
mount_cd9660_image \- Mount an ISO 9660 CD/DVD image

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na
mount_cd9660_image image-file mount-point
.ad
.fi

\" Optional sections
.SH "DESCRIPTION"
The
.B mount_cd9660_image
command mounts an ISO 9660 CD/DVD image file on the directory "mount-point".

The process requires creating a memory disk image using
.B mdconfig,
which must be detached using mdconfig in order to release the resources.

Hence, images mounted using
.B mount_cd9660_image
should always be unmounted using
.B umount_cd9660_image.

.SH "SEE ALSO"
umount_cd9660_image(1), mount_cd9660(1), mdconfig(1)

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
Jason Bacon

