#!/bin/sh

if [ $# != 2 ]; then
    printf "Usage: $0 image-file mount-directory\n"
    exit 1
fi

image=$1
dir=$2

# Find next available device number for mdconfig
devnum=0
while [ -e /dev/md${devnum} ]; do
    devnum=$((devnum+1))
done

# Create memory disk from image
mdconfig -a -t vnode -f $image -u ${devnum}

if [ ! -e $dir ]; then
    printf "$0: Error: $dir: No such directory.\n"
    exit 1
fi

if mount_cd9660 /dev/md$devnum $dir; then
    cat << EOM
Be sure to unmount using umount_image, not umount, or the memory disk
will not be detached.
EOM
fi

