#!/bin/sh

case $# in
1)
    ;;
*)
    while [ $# -gt 1 ]; do
	flags="$flags $1"
	shift
    done
    ;;
esac
	
dir="$1"

devnum=`mount | awk -v dir="$dir" '$3 == dir { print $1 }' | cut -c 8-`
if umount $flags $dir; then
    mdconfig -d -u $devnum
fi

